# recipe.yaml

{{ $imgname := or .imgname "dummy" }}
{{ $debupdate_hawkbit := or .debupdate_hawkbit "false" }}

architecture: arm64

actions:
- action: recipe
  recipe: ../debos/ospack.yaml
  variables:
    hostname: {{ $imgname }}

- action: recipe
  recipe: ../debos/osvideopack.yaml
  variables:
    multi_cam_rkaiq: true

- action: recipe
  recipe: ../debmodel/osmodelpack.yaml

- action: recipe
  recipe: ./osupdatepack.yaml
  variables:
    debupdate_hawkbit: {{ $debupdate_hawkbit }}

- action: recipe
  recipe: ./image.yaml
  variables:
    osinpack: osupdatepack
    imgname: {{ $imgname }}

- action: recipe
  recipe: ./swu.yaml
