name: Build and Release OpenAIA Debupdate 6TOPS

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: OpenAIA Debupdate 6TOPS runner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Remote Docker
      uses: docker/setup-buildx-action@v1

    - name: Set WORK_PATH
      run: |
        echo "WORK_PATH=$(dirname "${GITHUB_WORKSPACE}")" >> $GITHUB_ENV
        echo "WORK_PATH=${{ env.WORK_PATH }}"

    - name: Clone OpenAIA Debupdate
      run: |
        mkdir ${{ env.WORK_PATH }}/debupdate-openaia
        cp -rf ${{ env.WORK_PATH }}/debupdate ${{ env.WORK_PATH }}/debupdate-openaia
        cd ${{ env.WORK_PATH }}/debupdate-openaia
        git clone https://github.com/openaia/debos.git
        git clone https://github.com/openaia/debmodel.git

    - name: Download artifacts
      run: |
        cd ${{ env.WORK_PATH }}/debupdate-openaia
        cd debos && ./download-artifacts.sh && cd -
        cd debmodel && ./download-artifacts.sh && cd -
        cd debupdate && ./download-artifacts.sh && cd -

    - name: Build OpenAIA Debupdate
      run: |
        cd ${{ env.WORK_PATH }}/debupdate-openaia
        docker run --rm --tty \
          --privileged \
          --net host \
          -v ${{ env.WORK_PATH }}/debupdate-openaia:/home/build/shared \
          -w /home/build/shared ghcr.io/openaia/easy-build/build-debos:bookworm-v0.1 \
          sudo debos --memory=8Gb -t imgname:6tops debupdate/recipe.yaml

    - name: Upload output artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v2024.01-rc1"
        body: |
          ## OpenAIA Debomodel v2024.01-rc1
          - swupdate
          - .swup
        files: |
          ${{ env.WORK_PATH }}/debupdate-openaia/openaia-bullseye-6tops.bmap
          ${{ env.WORK_PATH }}/debupdate-openaia/openaia-bullseye-6tops.img.gz
          ${{ env.WORK_PATH }}/debupdate-openaia/osupdatepack-bullseye-arm64.tar.gz
          ${{ env.WORK_PATH }}/debupdate-openaia/update-image-6tops-v1.swu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
