name: Build and Release OpenAIA Debupdate Hawkbit 6TOPS

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: OpenAIA Debupdate Hawkbit 6TOPS runner
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone OpenAIA Debupdate
      run: |
        cd ${{ runner.workspace }}
        ls
        cd debupdate-actions
        ls

    - name: SWU file Upload  to Hawkbit server
      run: |
          cd ${{ runner.workspace }}
                    
          curl -i -X POST 'http://localhost:8080/rest/v1/softwaremodules' \
            -u 'admin:admin' \
            -H 'Content-Type: application/json' \
            -d '[{
            "vendor": "Edgeble",
            "name": "Neu6b swu image",
            "description": "Neu6b update image",
            "type": "os",
            "version": "1.0"
            }]'
        
          curl -i -X POST 'http://localhost:8080/rest/v1/softwaremodules/1/artifacts' \
            -u 'admin:admin' \
            -H 'Content-Type: multipart/form-data' \
            -F 'file=@update-image-6tops-v1.swu'  
