name: Build and Release OpenAIA Debupdate Hawkbit 6TOPS

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: OpenAIA Debupdate Hawkbit 6TOPS runner
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone OpenAIA Debupdate
      run: |
        cd ${{ runner.workspace }}
        ls

    - name: Upload output artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v2024.01-rc2"
        body: |
          ## OpenAIA Debomodel v2024.01-rc2
          - hawkbit
        files: |
           ${{ runner.workspace }}/debupdate-openaia/update-image-6tops-v1.swu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
