name: Build and Release OpenAIA Debupdate Hawkbit 6TOPS

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: OpenAIA Debupdate Hawkbit 6TOPS runner
    runs-on: self-hosted

    env:
      TAG_NAME: "v2024.04-rc1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone OpenAIA Debupdate
      run: |
        cd ${{ runner.workspace }}
        ls
        cd debupdate-actions

    - name: Upload output artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        body: |
          ## OpenAIA Debomodel ${{ env.TAG_NAME }}
          - hawkbit
        files: |
          ${{ runner.workspace }}/update-image-6tops-v1.swu
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Release
      uses: actions/checkout@v2
      with:
        ref: ${{ env.TAG_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Release Asset URL
      id: get_asset_url
      run: |
        ASSET_URL=$(curl -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/manojams/debupdate-actions/releases/tags/v2024.04-rc1 | jq -r '.assets[] | select(.name == "update-image-6tops-v1.swu") | .browser_download_url')
        echo "::set-output name=asset_url::$ASSET_URL"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Release Artifact
      run: |
        curl -H "Authorization: token ${GITHUB_TOKEN}" -LOJ "${{ steps.get_asset_url.outputs.asset_url }}"
        ls
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
