name: Build and Release OpenAIA Debupdate Hawkbit 6TOPS

on:
  push:
    branches:
      - master

jobs:
  build:
    permissions: write-all
    name: OpenAIA Debupdate Hawkbit 6TOPS runner
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Stop running Docker container
      run: |
        sudo docker stop $(sudo docker ps -q --filter ancestor=hawkbit/hawkbit-update-server:latest)
    
    - name: Run Docker in a new terminal
      run: gnome-terminal -- sudo docker run -p 8080:8080 hawkbit/hawkbit-update-server:latest
      
    - name: Clone OpenAIA Debupdate
      run: |
        cd ${{ runner.workspace }}
        ls
        cd debupdate-actions
        ls
    - name: run hawkbit swupdate action
      run: |
        cd ${{ runner.workspace }}
        ls
        ./v2-hawkbit-neu6-setup.sh
